owner: energyworldnet
repo: status

sites:
  - name: EWN Main Site
    url: https://www.energyworldnet.com
  - name: EWN Login
    url: https://auth.energyworldnet.com/static/login
  - name: EWN Web Client
    url: https://www.energyworldnet.com/PROIINET/Login
  - name: EWN Test Center Client
    url: https://www.energyworldnet.com/TestCenter/Complete
  - name: EWN SCORM & AICC Packages
    url: https://www.energyworldnet.com/RusticiEngine/defaultui/version.aspx

status-website:
  cname: status.energyworldnet.com
  favicon: https://www.energyworldnet.com/favicon.ico
  logoUrl: https://www.energyworldnet.com/wp-content/uploads/2020/08/logox2.png
  name: ''
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: Back to EWN
      href: https://www.energyworldnet.com
  theme: dark

commitMessages:
  commitAuthorName: EWN Bot
  commitAuthorEmail: ewnbot@energyworldnet.com

user-agent: ewnbot

i18n:
  footer: ''
