owner: energyworldnet
repo: status

sites:
  - name: Landing Page
    url: https://www.energyworldnet.com
  - name: Login
    url: https://auth.energyworldnet.com/static/login
  - name: Web App
    url: https://www.energyworldnet.com/PROIINET/Login
  - name: Testing Center
    url: https://www.energyworldnet.com/TestCenter/Complete
  - name: SCORM & AICC Content
    url: https://www.energyworldnet.com/RusticiEngine/defaultui/version.aspx

status-website:
  cname: status.energyworldnet.com
  favicon: https://www.energyworldnet.com/favicon.ico
  logoUrl: https://www.energyworldnet.com/wp-content/uploads/2020/08/logox2.png
  name: 'Status'
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Back to EWN
      href: https://www.energyworldnet.com
  theme: night

commitMessages:
  commitAuthorName: EWN Bot
  commitAuthorEmail: ewnbot@energyworldnet.com

user-agent: ewnbot

i18n:
  footer: ''
