owner: energyworldnet
repo: status

sites:
  - name: Landing Page
    url: https://www.energyworldnet.com
  - name: Login
    url: https://auth.energyworldnet.com/static/login
  - name: Web App
    url: https://app.energyworldnet.com/legacy/Login
  - name: Testing Center
    url: https://test-center.energyworldnet.com/Complete
  - name: SCORM & AICC Content
    url: https://scorm.energyworldnet.com/defaultui/version.aspx

status-website:
  cname: status.energyworldnet.com
  favicon: https://www.energyworldnet.com/favicon.ico
  logoUrl: https://raw.githubusercontent.com/energyworldnet/status/master/assets/ewn-logo.png
  name: 'Status'
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Back to EWN
      href: https://www.energyworldnet.com
  theme: night
  css: 'article.graph { background-image: none !important; }'

commitMessages:
  commitAuthorName: EWN Bot
  commitAuthorEmail: ewnbot@energyworldnet.com

user-agent: ewnbot

i18n:
  footer: ''
